# Generated by Django 5.1.2 on 2024-11-01 09:40

import django.db.models.deletion
import module.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50, null=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone_number', models.BigIntegerField()),
                ('timestamp', models.BigIntegerField(default=module.models.current_timestamp, editable=False)),
                ('user_password', models.CharField(default='default_password', max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_heading', models.CharField(blank=True, max_length=255)),
                ('note_body', models.TextField()),
                ('post_note_global', models.BooleanField(default=False, null=True)),
                ('created_at_timestamp', models.BigIntegerField(default=module.models.current_timestamp, editable=False)),
                ('updated_at_timestamp', models.BigIntegerField(default=module.models.current_timestamp, editable=False)),
                ('user_name_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='module.usermodel')),
            ],
        ),
    ]
